on:
  push:
    branches:
      - feature/1-changelog
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: 3-code-management-architecture
          path: /0-foundations/3-code-management-architecture
          default-branch: feature/1-changelog
          changelog-path: /0-foundations/3-code-management-architecture